# azure-pipelines.yml
trigger:
  branches:
    include:
      - main
      - dev
  paths:
    include:
      - src/
    exclude:
      - README.md

pr:
  branches:
    include:
      - main
      - dev

variables:
- template: variables.yml

stages:
  - stage: Build
    displayName: "Build WeatherApp"
    jobs:
      - template: templates/install.yml
      - template: templates/build.yml

  - stage: Deploy_Staging
    displayName: "Deploy to Staging (dev branch)"
    dependsOn: Build
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/dev'))
    jobs:
      - template: templates/deploy.yml
        parameters:
          environment: "staging"

  - stage: Deploy_Production
    displayName: "Deploy to Production (main branch)"
    dependsOn: Build
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
    jobs:
      - template: templates/deploy.yml
        parameters:
          environment: "production"
